### ISSUE TITLE
Disable overlay when using Pi 3 B+

### ISSUE THREAD

**Issue by Topdog1221** [Anodynous/stenogotchi#11]
**Describe the bug**
Blue Screen, not able to type anything in console.

**To reproduce**
1. Turn on pi
2. Login to root
3. Loads a few things and then blue screen.
**Expected behavior**

Honestly it makes sense that it happened as I am running it on a pi 3 model b+.
I just am wondering if I could remove the screen its trying to overlay as I wont need it until I get a raspberry pi zero 2 w for msrp.

**Software/hardware configuration (please complete the following information):**
 - Stenogotchi version: Latest
 - Plugin version: Latest
 - OS: DietPi Latest
 - Hardware: pi 3 model b+
**Additional Context**
I can login to dietpi, but have to reset if I want to go back to the keyboard.

**Comment by Anodynous** [comment]
I assume the overlay you refer to is the X display server which is needed by Plover to capture input when running headless. You can prevent it, and stenogotchi, from auto-launching by commenting out the lines in ~/.bash_profile.
