### ISSUE TITLE
Dvorak layout support

### ISSUE THREAD

**Issue by Shmuma** [Anodynous/stenogotchi#5]
Hi! 

First of all, thanks a lot for really nice project. It looks like the only option for ipad + steno keyboard.

Second, it might be useful to add to the documentation small note about extra configuration might be needed if 
target device we are connecting to uses non-querty layout for the keyboard. Specifically, I faced this on my ipad pro with magic keyboard. I'm using dvorak layout there and when I connect stenogotchi + steno keyboard, everything works, except the input text was transliterated from querty to dvorak (which makes input totally wrong). If I switch ipad keyboard layout back to query and reconnect, everything works.

To fix this, I added the following line to the beginning of .xinitrc:

```
setxkbmap -model pc105 -layout gb -variant dvorak
```

This enforces X11 to use dvorak layout and plover is doing proper transliteration of emitted keycodes.

**Comment by Anodynous** [comment]
This is a good suggestion. The information will also be valuable to anyone using a different input language than English.
