### ISSUE TITLE
First two letters capitalized with KPA

### ISSUE THREAD

**Issue by rmulligan** [Anodynous/stenogotchi#7]
When writing KPA to capitalize the next word it is capitalizing the first two letters of the word. Could this be due to low latency on the pi zero 2? 

For example:  TEst 

I'm not sure how the sequence is sent. Any ideas?

**Comment by Anodynous** [comment]
I have so far been unable to recreate this issue either on version 1 or 2 of the pi zero w. Is it occurring intermittently or constantly for you? Have you verified that the additional letter isn't capitalized already in the Plover output? You should be able to tell by enabling strokes/translations logging.

For reference I am using the ARMv8 64-bit image of DietPi Bullseye and the latest continuous build of Plover (plover-4.0.0.dev10+120.g4394ef1) on my pi zero 2 w. I am also running the dev branch of stenogotchi.

### PiZero2W installation notes:
At the time of writing some additional dependencies had to be installed on the 64-bit version of DietPi to set everything up.

To build several of the packages from source:

`apt-get install build-essential python3-dev`

To install dbus-python:

`apt-get install pkg-config libdbus-1-3 libdbus-1-dev libglib2.0-dev`

To install the stenogotchi plover_plugin:

`apt-get install libcairo2-dev`

**Comment by rmulligan** [comment]
I haven't seen this issue again after that initial encounter. Sorry for the hassle.
