### ISSUE TITLE
Waveshare eInk 2.13" HAT V3 not working

### ISSUE THREAD

**Issue by pweigele** [Anodynous/stenogotchi#9]
Hi, do you know if the Waveshare eInk 2.13" HAT is compatible with the Stenogotchi? I can't seem to get the display working. SPI and I2C states are on, but i2cdetect does not show anything.

**Comment by Anodynous** [comment]
It seems like the V3 version isn't compatible with the previous drivers, however the [compatible library code](https://github.com/waveshare/e-Paper/tree/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd) has been made available by Waveshare. I have created a new branch called 'waveshare3' which adds support for this new hardware version. I don't have any way to test it out myself so let me know how it works for you.

After switching to the new branch you'll need to add to your config.toml the below line:
`ui.display.type = 'waveshare_3'`

I2cdetect probably doesn't show anything as the screen uses SPI. You can check with lsmod if you have the required _spidev_ and _spi_bcm2835_ modules loaded.
`lsmod | grep spi`

**Comment by pweigele** [comment]
Thank you so much for updating this. I did configure the RPi02W following this branch, but the display is still inactive. I checked to see if the modules are loaded using lsmod as you suggested and got the following output: 
root@Stenogotchi:~# lsmod | grep spi
spidev                 20480  0
spi_bcm2835            20480  0

**Comment by pweigele** [comment]
All set now! Thank you for working with me and getting my Stenogotchi going!
